const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem
	];
};
self.C3_JsPropNameTable = [
	{xx: 0},
	{yy: 0},
	{Moved: 0},
	{Del: 0},
	{Block: 0},
	{HostBlock: 0},
	{Spot: 0},
	{BoardBg: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Browser: 0},
	{BtnReset: 0},
	{GameOver: 0},
	{txtScore: 0},
	{LocalStorage: 0},
	{Tween: 0},
	{FBlock: 0},
	{FSpot: 0},
	{SwipeDir: 0},
	{SwipeMaxDistance: 0},
	{StartTouchX: 0},
	{StartTouchY: 0},
	{BlocksMoving: 0},
	{Score: 0},
	{BestScore: 0},
	{BlockID: 0},
	{SpotID: 0},
	{Tag: 0},
	{ThereIsChance: 0}
];

self.InstanceType = {
	Block: class extends self.ISpriteInstance {},
	Spot: class extends self.ISpriteInstance {},
	BoardBg: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	txtScore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	FBlock: class extends self.ISpriteInstance {},
	FSpot: class extends self.ISpriteInstance {}
}